### ISSUE TITLE
Feature Request - Multiple options for Exporting usage data 

### ISSUE THREAD

**Issue by suhanacharya** [Stigmatoz/web-activity-time-tracker#10]
Currently the only option is export as CSV. But this exported data is just total usage time since installation :no_mouth:.

My request is to give the option to export data by Days with the usage of the websites per day. Just like how the extension visualizes usage by days :world_map:. 
It would be really cool to allow us to visualize it in other ways  :smiley:. But currently, the exported data is not of much use since it doesn't provide usage per day.

**Comment by Stigmatoz** [comment]
Hi. I will make a backup / restore function. The extension has received a lot of changes recently, and I will edit the data import work.

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday, so let's try to use this. Now you can export data for any days you choose to CSV format with time, number of visits, etc.
