### ISSUE TITLE
Better performance

### ISSUE THREAD

**Issue by d-bucur** [Stigmatoz/web-activity-time-tracker#101]
Looking at the task manager the extension regularly is one of the top utilizers of CPU with spikes of 3-6%.

![image](https://github.com/Stigmatoz/web-activity-time-tracker/assets/6576777/26b1f756-94fa-447a-8cd9-e269def5380e)

While I like the extension, I do feel that this has an unnecessary impact on my battery life, and should not be this high for what it is doing.

I would like for a way to reduce this, if not with proper optimizations, at least with a band aid like an option to increase the [tick intervals](https://github.com/Stigmatoz/web-activity-time-tracker/blob/c860e80ca71119a25e67a621b3b18b5fe0aa8e4b/src/scripts/common.js#L40-L41) to something like 10-30 seconds. I can really live without it not persisting data to a db every 5 seconds.

**Comment by d-bucur** [comment]
I can also have a look at it and submit a PR for this if there is interest to merge it.

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday, so let's try to use this.

**Comment by d-bucur** [comment]
I tried the new version, but I don't see any improvement. There are 5% spikes every 5 seconds and the intervals are still 1s/5s in the [new version](https://github.com/Stigmatoz/web-activity-time-tracker/blob/5c889184404c8ee0c34184b236a6e295b2fdfbb5/src/tracker.ts#L32). It's regularly one of the top CPU users in the task manager
