### ISSUE TITLE
Not tracking

### ISSUE THREAD

**Issue by xManufacturer** [Stigmatoz/web-activity-time-tracker#106]
Since a couple of days the app stop tracking and I have to concede permissions and refresh the app everytime I start Chrome. Please fix :(

![image](https://github.com/Stigmatoz/web-activity-time-tracker/assets/93669646/09b2f67c-1c6c-4f73-a7cb-a93854ca4579)

I have to deactivate and activate this one to start working, I dont know why, it started to fail few days ago. Thanks :)

**Comment by Stigmatoz** [comment]
The extension has been updated, so let's check it out and please tell me if everything is OK.

**Comment by xManufacturer** [comment]
Seems that now works perfectly fine. Thank you very much! :)
