### ISSUE TITLE
Microsoft edge splitting screen not recoreded

### ISSUE THREAD

**Issue by abdlla-nasser** [Stigmatoz/web-activity-time-tracker#125]
Microsoft edge splitting screen not recorded the site opened on the right side. and even blocking doesn't happen on the right. only the left side is seen for some reason

**Comment by Stigmatoz** [comment]
This is due to the fact that the extension only tracks the active tab, which has any user actions (mouse, keyboard). So, if the tab on the left was only open and there were no actions on it, the time for this tab is not taken into account.
