### ISSUE TITLE
[Notifications] Not seeing notification after the time set for websites 

### ISSUE THREAD

**Issue by pmg007** [Stigmatoz/web-activity-time-tracker#13]
I have set notifications with a custom message to show up once I cross a certain amount of time on quite a few websites. Although I do not get any notifications.
P.S. I am trying to use this extension in Microsoft Edge which is based on Chromium, and allows extensions from the Chrome web store. Is it possible that this issue is due to that?

**Comment by Stigmatoz** [comment]
Hi. This is most likely the problem.
I didn't tested extension on other browser, only chrome.

**Comment by pmg007** [comment]
Thanks for checking it out. I would like to inform that the notifications have started showing up recently. I will resolve the issue.
