### ISSUE TITLE
[Feature Request] Less clicks to turn site off

### ISSUE THREAD

**Issue by rajun274** [Stigmatoz/web-activity-time-tracker#130]
**Overview**

There's a game website that I try to stop myself from playing. Sometimes, I've already played a few rounds, and I want to not play any more for the remainder of the day. I open your extension, go to "Limit", and it takes many clicks just to set the timer to "00:00". Ideally, this should be a much easier process.

**Steps to reproduce**

1. Open the Options page
2. Go to Limit tab
3. Type the website name
4. Now trying to set the timer to "00:00" takes 5 clicks: press the timer, press "30", press 00, press "Select"
5. Press "Add website"

**Expected result**

Way less clicks to just disable a website.

**Actual result**

It takes many clicks to perform, what seems to be, an action that is very common among many users of your extension.

**Potential solutions**

One option is to have a "Disable now" button which updates the timer to "00:00", then the user presses "Add website." An even faster solution is a button called "Disable now and add website", which updates the timer to "00:00" and adds the website that's in the textbox to the list.

Thanks!

**Comment by Stigmatoz** [comment]
I'll do add this in the next release! Thanks!

**Comment by rajun274** [comment]
Thank you!!!
