### ISSUE TITLE
Weird backup

### ISSUE THREAD

**Issue by filborg** [Stigmatoz/web-activity-time-tracker#15]
Hi! Thank you for the great extension, love it. However, the CSV backup feature seems raw. It only exports the total time spent on specific websites in seconds. And I didn't even actually find where should I insert the CSV backup file, there's no "restore/import" option.

**Comment by Stigmatoz** [comment]
Hi. Thank you ;)
Yes, sure, I'll fix backup and make restore in next release.

**Comment by filborg** [comment]
Thanks, that would be awesome! @Stigmatoz @

**Comment by Stigmatoz** [comment]
Hi. Sorry for the delay.
I fixed the csv import and added data backup and restore.

**Comment by filborg** [comment]
@Stigmatoz
Hey, thanks a lot! 

But it seems that nothing has changed and as shown on the extension's page (Chrome extensions store) it was last updated on June 30. Perhaps I should install an update myself somehow?

**Comment by Stigmatoz** [comment]
@filborg You can see when a new version of the extension is approved at google.chrome.com. It can be 2-3 days or one week.

**Comment by filborg** [comment]
@Stigmatoz
Awesome, thanks again for your work!
