### ISSUE TITLE
Videos playing in background, or just background site tracking

### ISSUE THREAD

**Issue by shane99a** [Stigmatoz/web-activity-time-tracker#16]
Is that possible? Does chrome allow you track sites not currently active? I am on a multi monitor setup, so I can have multiple chrome windows visible, but only one would be active so it wouldn't be able to properly track accurately. For example if I have video playing in the inactive one, I would still want to track the inactive site.

**Comment by Stigmatoz** [comment]
Hello. 
This is not possible now. The extension only tracks the active tab. And if I want to get information about user actions (video, audio, etc.), I need to get full access permissions to the page.
