### ISSUE TITLE
Problems with the extension in Chrome v 84, stable, windows 10

### ISSUE THREAD

**Issue by akshit996** [Stigmatoz/web-activity-time-tracker#17]
Hello! Thank you for the great extension. The Web time tracker did not record my activity for a specific day though it was visited on the Chrome. please help and also tell me how can i locate it. The website i visited was only for like 30 seconds or so. How does the Webtime tracker collect info? Is there a minimum limit that only after you spend a certain time period the Webtime activity tracker will start recording?

**Comment by j0ner0n** [comment]
It should track immediately, at least does so for me for websites I visit for less than even 2 seconds. Possibly the extension was deactivated (e.g. running in a private chrome window where the extension has no access rights)?

**Comment by j0ner0n** [comment]
After you left the website and tracking failed, I doubt there is any way for you to recover this

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday, so let's try to use this.
