### ISSUE TITLE
Make time more legible.

### ISSUE THREAD

**Issue by Tamnac** [Stigmatoz/web-activity-time-tracker#27]
Currently the time appears to be white text, which makes it rather difficult to read on a browser with a white background. Adding a little dark background behind it would go a long way.

Thank you for you work.

**Comment by XAADE** [comment]
I do not agree. However, the blue box should be green when the timer is active. If the timer is not active, it should turn blue again. Because we cannot understand this. This will help us further.

**Comment by Tamnac** [comment]
@XAADE You do not think the time should be legible?

**Comment by XAADE** [comment]
> @XAADE You do not think the time should be legible?

It actually looks legible enough. Black text will be enough for you.

**Comment by Tamnac** [comment]
Black text would work as well, though then there would need to be a toggle for dark mode. That is why I suggested a background, as it would likely be simpler.

**Comment by Stigmatoz** [comment]
Hi guys.
I made some changes in the project.
Changed blue box to green box, when the timer is active.
![image](https://user-images.githubusercontent.com/23387046/108820998-0c006f80-75ce-11eb-9918-165500637dea.png)

And I added dark mode
![image](https://user-images.githubusercontent.com/23387046/108821354-84ffc700-75ce-11eb-83f5-baab1a36dddf.png)

You can update the extension already and try to using it. (version 1.6.0)
I am ready to listen to your proposal.

**Comment by XAADE** [comment]
> Hi guys.
> I made some changes in the project.
> Changed blue box to green box, when the timer is active.
> ![image](https://user-images.githubusercontent.com/23387046/108820998-0c006f80-75ce-11eb-9918-165500637dea.png)
> 
> And I added dark mode
> ![image](https://user-images.githubusercontent.com/23387046/108821354-84ffc700-75ce-11eb-83f5-baab1a36dddf.png)
> 
> You can update the extension already and try to using it. (version 1.6.0)
> I am ready to listen to your proposal.

This is a good development. Thank you.

**Comment by XAADE** [comment]
This is a good development. Thank you.
