### ISSUE TITLE
Eazy Feature request: List of sites with notifications

### ISSUE THREAD

**Issue by Emdad123** [Stigmatoz/web-activity-time-tracker#28]
Auto reminder messages (after every X minutes) on a website. 
the notification can be like: "You have spent 30 minutes on this site"
Please add this Feature.

**Comment by Stigmatoz** [comment]
Ok, I'll add this feature in the next release.

**Comment by Stigmatoz** [comment]
You can now specify this notification on the "Notification" page. Specify the site, time, and text of the notification.

**Comment by Emdad123** [comment]
thanks

**Comment by Emdad123** [comment]
oh, i actually wanted general/for all, not Specify, it will notify for all
website when I spent more than 30 min

**Comment by Emdad123** [comment]
but, it's ok as it is i guess.

**Comment by Danc2050** [comment]
This is a GREAT feature, but does not work for me on Google Chrome so far (see #40).

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday, so let's try to use this.
