### ISSUE TITLE
Fix the tool-tip on the Limit restrictions

### ISSUE THREAD

**Issue by petko10** [Stigmatoz/web-activity-time-tracker#30]
It's a minor usability fix for the tool-tip which got me a bit puzzled initially (I almost filed a bug for the limits not working). The text currently is: "Set the time you can spend on the site during the day. After this time, access to the site will be blocked." . If you know how the app works it's pretty clear. But combined with the time-selector which is more often used to choose a time-of-day and not a time duration - I got confused and thought the Limit has the function to cutoff access to the sites at some time of the day (till the end of the day or something like that). 
 Proposed correction: "Set the maximum time allowed on the site per day. After the this time has elapsed the site will be blocked.".
Or the second sentence can be something like "If you spend the allowed limit - the site will be blocked".

**Comment by Stigmatoz** [comment]
Hi. I fixed the tooltip title. (v1.6.1)
