### ISSUE TITLE
All time tab suggestions

### ISSUE THREAD

**Issue by albertopasqualetto** [Stigmatoz/web-activity-time-tracker#31]
In the all-time tab the most inactive day is obvious to be the current day if it is morning, so statistics are not realistic, the same is for the average by active days. A solution could be removing the current day from all time statistics.

**Comment by Stigmatoz** [comment]
Hello. I made some changes. I added a switch for general statistics. Now you can switch the general statistics with the current day and without the current day. (v1.6.1)
