### ISSUE TITLE
[Feature request] Disable limits temporarily

### ISSUE THREAD

**Issue by petko10** [Stigmatoz/web-activity-time-tracker#39]
Hi, I may be ill disciplined, but at times when I go over my limits I resort to disabling the extension. A more reasonable case: I've spent my Reddit minutes, but am researching some work-related topic that leads to some reddit threads. So I have to temporarily disable the extension. It would be nice to have an option in the extension popup to disable limits for some minutes, so that I don't have to disable the extension (and possibly forget to re-enable it), and that would also not skew the time-tracking analytics.

**Comment by Stigmatoz** [comment]
Hi. This is a very good idea. Several times I have been in the same situation. I am going to add this feature in the next release.

**Comment by Stigmatoz** [comment]
I added this feature in the release 1.6.4

**Comment by petko10** [comment]
Great, thanks for the addition and for all your other work on the extension, @Stigmatoz !
