### ISSUE TITLE
video web Statistics

### ISSUE THREAD

**Issue by bbfxier** [Stigmatoz/web-activity-time-tracker#4]
this extense only support youtube,but when i visit other video website,i donnot need move mouse or keyboard,so it has limit time on this site.

can you provide a list that i can add video site to it so that this extense can track time just like youtube without action detect?

**Comment by bbfxier** [comment]
i have download your source code,i find you use check dom to make sure youtube video is playing.
but i think mostly when you open a video site, you should watch video for sure.
so i think just provide a list to add video site and set action detect for Infinity

**Comment by Stigmatoz** [comment]
Extension must have access to the DOM page to check existing video and track it, and need add permissions for each target site with a video player

**Comment by bbfxier** [comment]
i think this can simply done by provide two option,one short time activity detect list(defualt),another long time activity detect for video site.
video site set a long time for activity detect,it may not accurate but for example 2hours it is enough to watch a video over.
so that i think there is no need to analysis each site

**Comment by luc99hen** [comment]
I have the same needs as https://github.com/Stigmatoz/web-activity-time-tracker/issues/38 . 
Since tracking h5 video sites are common user needs, I think this suggestion is considerable.

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday, so let's try to use this. If you watch and listen to something on the website, the time will be tracked.
