### ISSUE TITLE
Notification Not Showing Up

### ISSUE THREAD

**Issue by Danc2050** [Stigmatoz/web-activity-time-tracker#40]
I have a similar issue to #13, but the browser I am using is Google Chrome. I set a 1 minute time limit for www.youtube.com or www.google.com and never see a notification. I'd love this feature to work! Please let me know how I can help debug this issue (i.e., give output from devtools, etc.).

**Comment by Stigmatoz** [comment]
Hello. Sorry for delay. I see that after every update of the extension, the required permissions for showing notifications and tracking videos on YouTube and Netflix are removed. Check if you have been given notification permissions in settings.
I will check why this happens after updating the extension.

**Comment by janettecd** [comment]
I am having the same problem. Permissions are allowed and it's a fresh install & fully updated.
![screenshot](https://user-images.githubusercontent.com/99358776/153270377-a37a0593-9e21-43c3-9203-c3a7ae503b92.png)

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday, so let's try to use this.

**Comment by Nicolas-Puccio** [comment]
notifications not work in 2.2.5
limit works properly
