### ISSUE TITLE
Time tracking issue on Twitch.tv platform

### ISSUE THREAD

**Issue by TkKonstantin** [Stigmatoz/web-activity-time-tracker#41]
Time tracking on twitch.tv is not working properly, stoping after the setup timer for idle.
Most likely similar functionality to Youtube or Netflix is needed.

**Comment by Destaq** [comment]
I am experiencing the same issues with YouTube.

**Comment by TkKonstantin** [comment]
@Destaq, For youtube there is a special setting to track that. You should be able to find it here
![image](https://user-images.githubusercontent.com/45440034/154571751-5b6c2d4f-a6f9-4e6c-8041-4575798b361a.png)

**Comment by Destaq** [comment]
> @Destaq, For youtube there is a special setting to track that. You should be able to find it here
> 
> ![image](https://user-images.githubusercontent.com/45440034/154571751-5b6c2d4f-a6f9-4e6c-8041-4575798b361a.png)
> 
> 

I'm aware of that setting and have it turned on. However, recently, the tracker for YouTube seems to be randomly stopping - it will record up to a certain point, but then stop doing so and have an unchanged value.

**Comment by Stigmatoz** [comment]
In the latest version, you don't need to grant permissions for any video sites. The extension tracks whether you are watching a video or listening to audio. Please use the latest version for the store.
