### ISSUE TITLE
Time limits doesn't work

### ISSUE THREAD

**Issue by mxhsnowy** [Stigmatoz/web-activity-time-tracker#5]
Hi Stigmatoz, thank you for your wonderful extension. I have an issue that the daily restrictions seems doesn't work, I set a timer for a website but after the time I set I still accessed the website.

**Comment by Stigmatoz** [comment]
Hi. Thank you! Which site and domain name did you write in the limit settings?

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday, so let's try to use this.
