### ISSUE TITLE
Daily average pie chart

### ISSUE THREAD

**Issue by Cossty** [Stigmatoz/web-activity-time-tracker#58]
It would be very useful if we could see our daily average usage in a pie chart. 
Now we only know what our daily average is. One number is not enough.
Knowing only that your daily average is 6h is completely different from knowing that your daily average is 2h on YouTube, 1h on GitHub, 2h on Netflix, 1h on reddit.

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday. And I plan to add a dashboard with some detailed information about web usage.

**Comment by Stigmatoz** [comment]
You can update the extension. The version 2.0.11 has detailed statistics on any websites by day. You can see the average daily usage time on any websites.
