### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by langdon** [Stigmatoz/web-activity-time-tracker#64]
Could you please clarify your license? Your README says gpl 3 and your LICENSE file seems to be ccpl (although I am not sure what that is).

**Comment by kaushalyap** [comment]
@Stigmatoz I am also not sure what is CCPL? Creative commons do not have a license by that name.

**Comment by Stigmatoz** [comment]
Hi guys.
Now the license is MIT.

**Comment by langdon** [comment]
thanks!!
