### ISSUE TITLE
Feature : Update time icon every X minutes instead of seconds

### ISSUE THREAD

**Issue by oblx** [Stigmatoz/web-activity-time-tracker#7]
Hi,

First thank for your application, I switched from FF to a chromium based browser and I used to have "Mind the time". However, is it possible to set the minimum amount of time before visually updating the clock ?

Like instead of every second -which is visually disturbing during the first 60 ones- having a setting to every minute or 5 minute.

Keep up the great job :)

**Comment by oblx** [comment]
Oh sorry, I should have used the store form, I got too used to report on github...

**Comment by Stigmatoz** [comment]
Hi. I'm sorry it's so late. You can disable time tracking in the icon in settings.
If I make a setting for every minute or 5 minutes it will look like incorrect operation.

**Comment by oblx** [comment]
Hi, thanks for replying !
I got used to that small icon moving every second now that I spent minutes on my usual websites. I would say it's perfect, great job 👍
