### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by NormTurtle** [Stigmatoz/web-activity-time-tracker#74]
how to i import export 
tracked information  

from old browser to new browser 

such as i installed by browser again  . so how can i get all the data back?

**Comment by pauloeli** [comment]
If you have the old directory, you just need to copy the original folder to the new installation. I indicate to do that with the browser closed.

```
# data
.config/BraveSoftware/Brave-Browser/Default/Local Extension Settings/hhfnghjdeddcfegfekjeihfmbjenlomm

# instalattion version reference (maybe you need to copy the second dir too)
.config/google-chrome/Default/Extensions/hhfnghjdeddcfegfekjeihfmbjenlomm/1.7.2_0
```

After that, all my history are loaded. 
I hope I have helped you.

**Comment by Stigmatoz** [comment]
You can export data to CSV for any date range
![image](https://github.com/Stigmatoz/web-activity-time-tracker/assets/23387046/4329b23e-3428-4d26-8368-8caba533160f)

And you can backup/restore data. This feature was added in version 2.0.7
![image](https://github.com/Stigmatoz/web-activity-time-tracker/assets/23387046/64b802ae-b180-4316-9453-878cadafcf7a)
