### ISSUE TITLE
export the  data of time chart to CSV format?

### ISSUE THREAD

**Issue by ningxia2022** [Stigmatoz/web-activity-time-tracker#77]
I want to see the time chart by days, it seems that I can only view today's time chart,, not yesterday or before today.

I also want to export count of visits  to CSV format by days

I hope you can meet my functional suggestions. Thank you

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday, so let's try to use this. Now you can export data for any days you choose to CSV format with time, number of visits, etc.
