### ISSUE TITLE
Fix: Change Text Color of text in Bar chart

### ISSUE THREAD

**Issue by UtkarshM-hub** [Stigmatoz/web-activity-time-tracker#79]
## What is happening
Text Color of Dates in bar chart remains black in dark mode. It makes it harder to see them.

## What is expected
Text color of Dates should change to white when set to dark mode

![Screenshot (104)](https://user-images.githubusercontent.com/70505181/189877063-9143231e-e2a1-4dce-98d1-a3d419e55797.png)

**Comment by Stigmatoz** [comment]
Hi. 
I see it. I will change the color in the next release.
