### ISSUE TITLE
如果能支持中文就好了

### ISSUE THREAD

**Issue by vmuu** [Stigmatoz/web-activity-time-tracker#80]
在中国还是有很多用户愿意使用这个的，但是我没有找到语言切换按钮，感觉不是特别方便

**Comment by 3315531721** [comment]
I agree you!

**Comment by sheepzh** [comment]
真巧我也开发了一个，原生中文
https://github.com/sheepzh/timer
@vmuu @3315531721

**Comment by 3315531721** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近有事，无法亲自回复你的邮件。我将在事情结束后，尽快给你回复。

**Comment by 3315531721** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近有事，无法亲自回复你的邮件。我将在事情结束后，尽快给你回复。
