### ISSUE TITLE
[Feature Request] Categories for urls

### ISSUE THREAD

**Issue by enderahmetyurt** [Stigmatoz/web-activity-time-tracker#81]
The urls would have categories, and they can be sorted by categories. We can understand how many time we spend in a category daily/weekly so on.

It would be something like screenshot below.

![Screenshot 2022-11-11 at 10 08 21](https://user-images.githubusercontent.com/447588/201285798-9ad4348c-e0e4-445a-8fc0-9a2426a134e3.png)

**Comment by Stigmatoz** [comment]
Hi. 
It's a really good idea, and I've already thought about it.
First of all, I have to go to manifest v3 and then I will work on this feature.
