### ISSUE TITLE
Edge Addons store updates

### ISSUE THREAD

**Issue by albertopasqualetto** [Stigmatoz/web-activity-time-tracker#83]
Hello, I downloaded your extension from the [Edge Addons store](https://microsoftedge.microsoft.com/addons/detail/web-activity-time-tracker/eepmlmdenlkkjieghjmedjahpofieogf) but the last update was on 28 of November 2020, will you update it?

**Comment by Stigmatoz** [comment]
The extension was updated to the last version in Edge. Please update this.
