### ISSUE TITLE
Can I revert to how it was before

### ISSUE THREAD

**Issue by Ignacio-Garro** [Stigmatoz/web-activity-time-tracker#84]
The asthetic of the addon has changed, I dont like the grey and the design is just not as clean, can you make it pretty like before

**Comment by Ignacio-Garro** [comment]
I think the problem is just in dark mode, what I use, so can you make dark mode better looking?

**Comment by Ignacio-Garro** [comment]
also just want to say that I still love this addon, so thank you for all your work

**Comment by Stigmatoz** [comment]
Hi. 
I thought about your opinion and studied some information about the dark mode. I found several articles in which one of the most recommended colors for dark mode is #121212. Google also recommends this.
I will change the color in the next release.

**Comment by Ignacio-Garro** [comment]
Yhea that would be great, I'm a fan of darker blacks, have a nice day
