### ISSUE TITLE
Editing time limits not working

### ISSUE THREAD

**Issue by TNTRedstone** [Stigmatoz/web-activity-time-tracker#85]
When I try to edit a time limit it does nothing and returns this error in the console:
"Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at actionEditSite (settings.js:472:31)
    at HTMLImageElement.<anonymous> (settings.js:413:9)"

**Comment by Pr3dat0rGam1ng** [comment]
Its giving me the same error
