### ISSUE TITLE
can't delete limits

### ISSUE THREAD

**Issue by zeoxion** [Stigmatoz/web-activity-time-tracker#92]
today i added a limit to a website domain and now i found out i can't delete it. 
I test a few times and restart the browser and the computer but couldn't solve the problem. 
I re-install the extension and didn't work either. 
idk it is bug or not. And sincerely looking forward to your help. thx

**Comment by Theo-Dancoisne** [comment]
Same issue with the "Ignored list of domain", I check this out and the event listener doesn't have a callback containing the key "path", but i think you will be more intersted by this function : https://developer.mozilla.org/en-US/docs/Web/API/Document/elementsFromPoint 😉(x & y are contained in the mouse click callback).
![image](https://user-images.githubusercontent.com/105285931/217336408-840f233c-e9eb-40cc-8728-6748319ab2f3.png)

**Comment by Stigmatoz** [comment]
@zeoxion Which version are you using right now? This bug was fixed in pr #88, version 1.7.2.

**Comment by zeoxion** [comment]
> @zeoxion Which version are you using right now? This bug was fixed in pr #88, version 1.7.2.

oh I see. Thx for replying. I download the extension from Microsoft Edge Adds-on and the version is 1.5.2. You may like to update the extension there.
