### ISSUE TITLE
[Feature Request] Notification for total time spent on the browser

### ISSUE THREAD

**Issue by tommy9771** [Stigmatoz/web-activity-time-tracker#96]
Can there be an option to display the total time spent on the browser in the icon and pop-up notification? (Instead of individual website)

**Comment by Stigmatoz** [comment]
Thank you for request. Yes, it's really useful feature - a notification with notification with total time for the day. I will do it.

**Comment by tommy9771** [comment]
> Thank you for request. Yes, it's really useful feature - a notification with notification with total time for the day. I will do it.

Thank you for your attention and efforts.

**Comment by Stigmatoz** [comment]
A new version with a new codebase was released yesterday, so let's try to use this. There is notification in the end of the day with summary web usage.
